name: grocery_prokit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.4.8
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.1.0

  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  # MAP
  google_maps_flutter: ^2.0.11
  geolocator: ^7.3.1
  geocoding: ^2.0.0

  #Grocery
  cached_network_image: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "images/grocery/grocery_ic_logo.png"
  adaptive_icon_background : "#00c97b"

flutter:

  uses-material-design: true

  assets:
   - images/grocery/
   - images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
