name: dating_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  #Dating App
  cached_network_image: ^3.1.0
  multi_image_picker: ^4.8.00
  photo_view: ^0.12.0
  card_swiper: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/

